add phone
woyager69/first-command-project pull request #13
Opened 2022-01-29 18:28 UTC by MykolaOdiehov

2022-01-29 22:06 UTC, SuDenDimon requested changes
исправьте все медиа запросы для мобильной версии на такие: @media screen and (min-width: 320px)

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +    @media(max-width:768px){
Уберите этот медиа запрос

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +    @media (min-width:0px) and (max-width:480px){
начинаем верстать от мобильной версии от 320px , значит во всех медиа запросах для мобильной версии min-width: 320px

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +    @media (min-width:0px) and (max-width:480px){
и max-width в медиа-запросе нам пока что не нужен

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
>  height: 525px;
не задавайте фиксированную высоту блоку регулируйте ее свойством  padding

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
>      width: 329px;
удалите это свойство

2022-01-29 22:06 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +margin-left: auto ;
так задавать нельзя удалите это лишнее

2022-01-29 22:06 UTC, SuDenDimon commented on src/partials/products.html
> +                        <p>Lorem ipsum dolor sit amet, <br> consectetur adipiscing elit,<br> sed do eiusmod tempor <br> incididunt ut labore et</p>
удаляйте все <br>, зачем они здесь?

2022-01-30 20:07 UTC, woyager69 approved these changes

2022-01-30 20:07 UTC, woyager69 approved these changes

2022-01-30 20:08 UTC, woyager69 approved these changes

2022-01-30 20:08 UTC, woyager69 approved these changes

2022-01-30 20:08 UTC, woyager69 approved these changes

2022-01-30 20:08 UTC, woyager69 approved these changes

2022-01-30 20:09 UTC, woyager69 approved these changes

2022-01-30 20:09 UTC, woyager69 approved these changes

2022-01-30 20:10 UTC, merged