Feature/products
woyager69/first-command-project pull request #36
Opened 2022-01-31 18:31 UTC by MykolaOdiehov

2022-01-31 22:48 UTC, SuDenDimon requested changes

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +    @media (min-width:320px) {
Если мы задаём медиа правило с мин видс 320 и задаём ему стили, в данном случае падинги, то они будут действовать на отрезке от 320 и до бесконечности пока мы не зададим новое медиа правило с другим значением мин видс, поэтому медиа правила для для 768 и 1280 для данного селектора не имеет смысла  задавать с такими же значениями их можно просто убрать

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +    @media ( min-width:768px){
а здесь нужно задавать в медиаправила для ширин 768 и 1280 только те стили которые меняются
например: 
.text-item {
    font-family: DM Sans;
    font-style: normal;
    font-weight: bold;
    font-size: 12px;
    line-height: 170%;
    letter-spacing: 0.04em;
    color: #000;
    padding: 15px 0 40px 0;
    margin-bottom: 40px;
    max-width: 260px;
    text-transform: none;
    @media screen and (min-width: 768px) {
        font-size: 14px;
        line-height: 174%;
    }
    @media screen and (min-width: 1280px) {
        font-size: 16px;
        line-height: 176%;
        letter-spacing: 0.02em;
    }
}

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +        flex-basis: calc((100% - 20 * 20px ) / 3)
у вас что 20 элементов в строке?

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +            margin-right: auto;
зачем здесь марджин райт авто и марджин лэфт авто?

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +            @media ( min-width:768px){
здесь можно задать медиа запрос @media screen and (min-width: 768px) and (max-width: 1179px) {
записать стили для данного участка}

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +            @media(min-width:1280px){
тогда это медиаправило нужно убрать

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +                @media(min-width:220px){
Это что?

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +        @media ( min-width:768px){
убрать

2022-01-31 22:48 UTC, SuDenDimon commented on src/sass/layout/_products.scss
> +            margin-left: auto;
это зачем? зачем каждому элементу дублировать стили??!!!

2022-02-01 13:18 UTC, closed without merging

2022-02-01 13:19 UTC, woyager69 commented
переход секции в разработку другому члену команды